name: PluginTeste
author: IceNdev
version: 1.0
main: me.icendev.PluginTeste.Main
description: Plugin de Teste
commands:
  coins:
    description: Ver coins atuais
  sc:
    description: Chat da staff
  cage:
    description: Staff command